# Generated by Django 4.2.2 on 2023-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(max_length=100000, verbose_name='商品説明'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='release_date',
            field=models.DateField(blank=True, help_text='2023-06-22のような形式で入力してください', null=True, verbose_name='発売日'),
        ),
    ]
